<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TT0022324" ignored="0" name="Default test" tests="4" failures="0" timestamp="2020-06-28T12:12:42 EET" time="0.07" errors="0">
  <testcase name="@BeforeTest initialize" time="0.016" classname="hepsiburada.DemoHomework.Homepage">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at hepsiburada.DemoHomework.Homepage.initialize(Homepage.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest initialize -->
  <testcase name="@AfterTest teardown" time="-1.593335562177E9" classname="hepsiburada.DemoHomework.Homepage">
    <skipped/>
  </testcase> <!-- @AfterTest teardown -->
  <testcase name="goAccount" time="0.0" classname="hepsiburada.DemoHomework.Homepage">
    <skipped/>
  </testcase> <!-- goAccount -->
  <testcase name="goAraundOnProducts" time="0.0" classname="hepsiburada.DemoHomework.Homepage">
    <skipped/>
  </testcase> <!-- goAraundOnProducts -->
  <testcase name="goBasket" time="0.0" classname="hepsiburada.DemoHomework.Homepage">
    <skipped/>
  </testcase> <!-- goBasket -->
  <testcase name="verifyProducts" time="0.0" classname="hepsiburada.DemoHomework.Homepage">
    <skipped/>
  </testcase> <!-- verifyProducts -->
</testsuite> <!-- Default test -->
